notifications:
  email: false

language: node_js

script:
  - mkdir deploy
  - zip deploy/deploy.zip index.js

deploy:
  - provider: s3
    access_key_id: $AWS_ACCESS_KEY_ID
    secret_access_key: $AWS_SECRET_ACCESS_KEY
    bucket: "terraform-practice-builds-ap-southeast-2"
    local_dir: deploy
    skip_cleanup: true
    region: "ap-southeast-2"