language: node_js

script:
  - mkdir deploy
  - zip deploy/deploy.zip index.js

deploy:
  - provider: s3
    bucket: "terraform-practice-builds-ap-southeast-2"
    local_dir: deploy
    skip_cleanup: true
    region: "ap-southeast-2"