notifications:
  email: false

language: node_js

before_install:
  - wget https://releases.hashicorp.com/terraform/0.9.6/terraform_0.9.6_linux_amd64.zip
  - unzip terraform_0.9.6_linux_amd64.zip

script:
  - mkdir deploy
  - zip deploy/deploy.zip index.js
  - ./terraform init
  - ./terraform plan

deploy:
  - provider: s3
    access_key_id: $AWS_ACCESS_KEY_ID
    secret_access_key: $AWS_SECRET_ACCESS_KEY
    bucket: "terraform-practice-builds-ap-southeast-2"
    local_dir: deploy
    skip_cleanup: true
    region: "ap-southeast-2"

  - provider: script
    script: ./terraform apply
    skip_cleanup: true